const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

const USER_LOGOUT = "USER_LOGOUT";

const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

const USER_DETAILS_REQUEST = "USER_REGISTER_REQUEST";
const USER_DETAILS_SUCCESS = "USER_REGISTER_SUCCESS";
const USER_DETAILS_FAILURE = "USER_REGISTER_FAILURE";

const USER_UPDATE_REQUEST = "USER_REGISTER_REQUEST";
const USER_UPDATE_SUCCESS = "USER_REGISTER_SUCCESS";
const USER_UPDATE_FAILURE = "USER_REGISTER_FAILURE";
const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export {
  USER_LOGIN_FAILURE,
  USER_LOGIN_REQUEST,
  USER_LOGIN_SUCCESS,
  USER_LOGOUT,
  USER_REGISTER_REQUEST,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_FAILURE,
  USER_DETAILS_REQUEST,
  USER_DETAILS_SUCCESS,
  USER_DETAILS_FAILURE,
  USER_UPDATE_FAILURE,
  USER_UPDATE_REQUEST,
  USER_UPDATE_SUCCESS,
  USER_UPDATE_RESET,
};
