const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

const USER_LOGOUT = "USER_LOGOUT";

const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE";
const USER_DETAILS_RESET = "USER_DETAILS_RESET";

const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";
const USER_UPDATE_RESET = "USER_UPDATE_RESET";

const USER_LIST_REQUEST = "USER_LIST_REQUEST";
const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
const USER_LIST_FAILURE = "USER_LIST_FAILURE";
const USER_LIST_RESET = "USER_LIST_RESET";

const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";

const USER_UPDATE_ADMIN_REQUEST = "USER_UPDATE_ADMIN_REQUEST";
const USER_UPDATE_ADMIN_SUCCESS = "USER_UPDATE_ADMIN_SUCCESS";
const USER_UPDATE_ADMIN_FAILURE = "USER_UPDATE_ADMIN_FAILURE";
const USER_UPDATE_ADMIN_RESET = "USER_UPDATE_ADMIN_RESET";

export {
  USER_LOGIN_FAILURE,
  USER_LOGIN_REQUEST,
  USER_LOGIN_SUCCESS,
  USER_LOGOUT,
  USER_REGISTER_REQUEST,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_FAILURE,
  USER_DETAILS_REQUEST,
  USER_DETAILS_SUCCESS,
  USER_DETAILS_FAILURE,
  USER_UPDATE_FAILURE,
  USER_UPDATE_REQUEST,
  USER_UPDATE_SUCCESS,
  USER_UPDATE_RESET,
  USER_DETAILS_RESET,
  USER_LIST_FAILURE,
  USER_LIST_REQUEST,
  USER_LIST_SUCCESS,
  USER_LIST_RESET,
  USER_DELETE_FAILURE,
  USER_DELETE_REQUEST,
  USER_DELETE_SUCCESS,
  USER_UPDATE_ADMIN_FAILURE,
  USER_UPDATE_ADMIN_REQUEST,
  USER_UPDATE_ADMIN_RESET,
  USER_UPDATE_ADMIN_SUCCESS
};
